common:
  http:
    enabled: true
    port: 8080
  ws:
    enabled: false
    port: 8881

storage:
  token: ""
  url: "http://storage.local:8880"
ethereum:
  interaction: "http://ethereum-interaction.local:8882"
  nodes:
    chain1: "https://data-seed-prebsc-1-s1.bnbchain.org:8545"
  token: ""
  retries: 1
  retry_delay: 10
  rate_limit: 100000
cosmos:
  node:
    json_rpc: "sekai.local:9090"
    tendermint: "http://sekai.local:26657"
  tx_modes:
    sync: true
    async: true
    block: true
  gw_timeout: 30
  interaction: "http://cosmos-interaction.local:8884"
  token: ""
  retries: 1
  retry_delay: 10
  rate_limit: 2

p2p:
  id: "1"
  address: "127.0.0.1:9000"
  peers: []
  max_peers: 2

balancer:
  window_size: 60
  threshold: 0.2
