common:
  http:
    enabled: true
    port: 8883
  ws:
    enabled: false
    port: 8081

storage:
  token: ""
  url: "http://storage.local:8880"
  email: ""
  password: ""
  mongo_collection_name: "cosmos"
notifier:
  token: "lafijsiadnm/a@@#lsa$fd8f"
  url: "http://localhost:8885"
  sender_id: "Cosmos"

node_address: "http://sekai.local:26657"
start_block: 1
tx_type: "/kira.bridge.MsgChangeCosmosEthereum"
sleep_duration: 2
handle_blocks: true
skip_faile_tx: false

